title: Geopastore
description: 
sass:
  sass_dir: assets/css
show_excerpts: true
excerpt_separator: <!--more-->

url: "https://geopastore.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
